### ISSUE TITLE
libz.dylib

### ISSUE THREAD

**Issue by NikJaySix** [reidmain/Xcode-Project-Templates#1]
This is not an issue but rather a fix for the known bug. I worked out a way to include the libz.dylib file in a template i am trying to put together for another SDK 

I created an alias to the lib folder inside the new template folder. Then created a definition 

``` XML
<key>Libraries/libz.dylib</key>
        <dict>
            <key>Group</key>
            <string>Libraries</string>
            <key>Path</key>
            <string>lib/libz.dylib</string>
        </dict>
```

Then created a node

``` XML
<string>Libraries/libz.dylib</string>
```

When you create your project, a group called "Libraries" is created inside the project and libz.dylib sits inside that and is also added to Link binary with libraries under build phases.

This works for me so I hope this works for you.

I was intending to include Testflight into my template as well so your template is very useful!

**Comment by reidmain** [comment]
Interesting solution. I found some workarounds to add libz.dylib but they all resulted in it being missing from the "Link Binary With Libraries" section.

Do you just hardcode the alias to the lib directory? Ideally I'd like to make it so I don't have to release a update each time a new Xcode version is released.

**Comment by reidmain** [comment]
I have replaced TestFlight with HockeyApp so this issue is now moot.
